export const allItems = [
    {_id: "100",title: "All Departments"},
    {_id: "101",title: "Health & Hohusehold"},
    {_id: "102",title: "Home & Kitchen"},
    {_id: "103",title: "Kindle Store"},
    {_id: "104",title: "Luggage"},
    {_id: "105",title: "Men's Fashion"},
    {_id: "106",title: "Mivies & TV"},
    {_id: "107",title: "Music, CDs & Vinyl"},
    {_id: "108",title: "Pet Suplies"},
    {_id: "109",title: "Prive Video"},
    {_id: "110",title: "Software"},
    {_id: "111",title: "Sports & Outdoors"},
    {_id: "112",title: "Tools & Home Improvements"},
    {_id: "113",title: "Toys & Games"},
    {_id: "114",title: "Video Games"},
    {_id: "115",title: "Women's Fashion"},
    {_id: "116",title: "Baby"},
    {_id: "117",title: "Personal Care"},
  ]